package stacks

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// SiteConfig describes one nginx server block generated by Exposely.
type SiteConfig struct {
	// ServerName is the local host the site answers for (e.g. app.test).
	ServerName string
	// Root is the document root directory (e.g. <project>/public for
	// Laravel, the project folder itself for static sites).
	Root string
	// PHP bool: when true .php requests are fastcgi_pass'ed to
	// PHPPort; when false the site is served as static files.
	PHP bool
	// PHPPort is the FastCGI port php-cgi listens on (e.g. 9000).
	PHPPort int
	// ListenPort is the HTTP port nginx binds for this site.
	ListenPort int
	// Index files for directory requests.
	Index []string
}

// RenderNginxConf builds a complete, self-contained nginx.conf that
// serves the supplied sites. It never modifies the user's nginx install:
// the generated file lives in Exposely's own data directory and is passed
// to nginx with `-c` at start time.
//
// nginxRoot is the nginx installation directory (where nginx.exe lives);
// its conf/mime.types is referenced by absolute path so relative-path
// resolution quirks on Windows cannot break the config.
func RenderNginxConf(nginxRoot string, listenPort int, sites []SiteConfig) string {
	mimeTypes := filepath.Join(nginxRoot, "conf", "mime.types")
	var b strings.Builder

	b.WriteString("# Generated by Exposely — safe to delete, regenerated on every stack start.\n")
	b.WriteString("worker_processes  1;\n\n")
	b.WriteString("events {\n    worker_connections  1024;\n}\n\n")
	b.WriteString("http {\n")
	b.WriteString("    include       " + quotePath(mimeTypes) + ";\n")
	b.WriteString("    default_type  application/octet-stream;\n\n")
	b.WriteString("    sendfile           on;\n")
	b.WriteString("    keepalive_timeout  65;\n\n")

	if len(sites) == 0 {
		// Always emit at least one server so nginx does not fail to
		// start with zero server blocks.
		sites = []SiteConfig{{
			ServerName: "localhost",
			Root:       nginxRoot,
			ListenPort: listenPort,
			Index:      []string{"index.html"},
		}}
	}

	for _, site := range sites {
		writeServerBlock(&b, site)
	}

	b.WriteString("}\n")
	return b.String()
}

func writeServerBlock(b *strings.Builder, site SiteConfig) {
	listen := site.ListenPort
	if listen <= 0 {
		listen = 8090
	}
	serverName := strings.TrimSpace(site.ServerName)
	if serverName == "" {
		serverName = "localhost"
	}
	root := strings.TrimSpace(site.Root)
	if root == "" {
		root = "."
	}

	fmt.Fprintf(b, "    server {\n")
	fmt.Fprintf(b, "        listen       %d;\n", listen)
	fmt.Fprintf(b, "        server_name  %s;\n", serverName)
	fmt.Fprintf(b, "        root         %s;\n", quotePath(root))
	fmt.Fprintf(b, "        index        %s;\n", joinIndex(site.Index))
	fmt.Fprintf(b, "\n")
	fmt.Fprintf(b, "        location / {\n")
	fmt.Fprintf(b, "            try_files $uri $uri/ /index.php?$query_string;\n")
	fmt.Fprintf(b, "        }\n")

	if site.PHP && site.PHPPort > 0 {
		fmt.Fprintf(b, "\n        location ~ \\.php$ {\n")
		fmt.Fprintf(b, "            fastcgi_pass   127.0.0.1:%d;\n", site.PHPPort)
		fmt.Fprintf(b, "            fastcgi_index  index.php;\n")
		fmt.Fprintf(b, "            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;\n")
		fmt.Fprintf(b, "            include        fastcgi_params;\n")
		fmt.Fprintf(b, "        }\n")
	}

	b.WriteString("    }\n\n")
}

func joinIndex(index []string) string {
	trimmed := make([]string, 0, len(index))
	for _, i := range index {
		if s := strings.TrimSpace(i); s != "" {
			trimmed = append(trimmed, s)
		}
	}
	if len(trimmed) == 0 {
		return "index.html index.php"
	}
	return strings.Join(trimmed, " ")
}

// quotePath wraps a path in double quotes when it contains spaces so the
// generated nginx.conf survives Windows install paths like
// C:\Program Files\nginx.
func quotePath(path string) string {
	path = strings.TrimSpace(path)
	if strings.ContainsAny(path, " \t") {
		return `"` + strings.ReplaceAll(path, `\`, `/`) + `"`
	}
	return strings.ReplaceAll(path, `\`, `/`)
}

// WriteFile writes content to path, creating parent directories. Used for
// the generated nginx.conf.
func WriteFile(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}
