package stacks

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
)

// DetectPhpMyAdmin locates an existing phpMyAdmin install on this
// machine. Exposely does not download anything: it reuses whatever the
// user already has (EnvKit, Laragon, XAMPP, or a manual zip extract).
// The first directory containing an index.php under any candidate path
// wins.
//
// The returned value is the directory that should be used as the nginx
// document root for the phpmyadmin vhost.
func DetectPhpMyAdmin() (string, bool) {
	for _, candidate := range phpMyAdminCandidates() {
		if isPhpMyAdminDir(candidate) {
			return candidate, true
		}
	}
	return "", false
}

// phpMyAdminCandidates lists the well-known install locations across
// the popular local dev stacks, newest-first within each stack.
func phpMyAdminCandidates() []string {
	var out []string

	switch runtime.GOOS {
	case "windows":
		// EnvKit keeps versioned copies under services\phpmyadmin\<ver>.
		if entries, err := filepath.Glob(`C:\ProgramData\envkit\services\phpmyadmin\*`); err == nil {
			out = append(out, newestDirs(entries)...)
		}
		// Laragon default layout.
		for _, base := range []string{`C:\laragon`, `D:\laragon`} {
			out = append(out, filepath.Join(base, "etc", "apps", "phpmyadmin"))
		}
		// XAMPP.
		out = append(out, `C:\xampp\phpMyAdmin`)
		// Manual zip extracts.
		out = append(out,
			`C:\phpmyadmin`,
			filepath.Join(env("PROGRAMFILES"), "phpMyAdmin"),
			filepath.Join(env("LOCALAPPDATA"), "Programs", "phpMyAdmin"),
		)
	case "darwin":
		home := env("HOME")
		out = append(out,
			"/Applications/phpMyAdmin",
			filepath.Join(home, "phpmyadmin"),
			"/usr/share/phpmyadmin",
			"/opt/homebrew/share/phpmyadmin",
		)
	default:
		out = append(out,
			"/usr/share/phpmyadmin",
			"/var/www/html/phpmyadmin",
			"/opt/phpmyadmin",
		)
	}

	return out
}

// newestDirs sorts versioned sibling directories newest-first using a
// simple descending name compare; version strings like "5.2.3" sort
// correctly enough for the handful of entries we deal with.
func newestDirs(entries []string) []string {
	// Simple insertion sort, descending.
	sorted := append([]string(nil), entries...)
	for i := 1; i < len(sorted); i++ {
		for j := i; j > 0 && sorted[j] > sorted[j-1]; j-- {
			sorted[j], sorted[j-1] = sorted[j-1], sorted[j]
		}
	}
	return sorted
}

func isPhpMyAdminDir(path string) bool {
	if strings.TrimSpace(path) == "" {
		return false
	}
	info, err := os.Stat(path)
	if err != nil || !info.IsDir() {
		return false
	}
	// phpMyAdmin's front controller plus its signature vendor layout.
	if _, err := os.Stat(filepath.Join(path, "index.php")); err != nil {
		return false
	}
	if _, err := os.Stat(filepath.Join(path, "vendor", "phpmyadmin")); err == nil {
		return true
	}
	// Some distributions flatten vendor; README + index.php is still a
	// strong signal.
	if _, err := os.Stat(filepath.Join(path, "README")); err == nil {
		return true
	}
	return false
}

func env(key string) string {
	return os.Getenv(key)
}

// PhpMyAdminServerConfig renders config.user.inc.php content that
// points phpMyAdmin at the Exposely-managed MariaDB (and optionally an
// extra server). Written into the phpMyAdmin directory on first open so
// the login screen pre-selects the right server.
func PhpMyAdminServerConfig(host string, port int) string {
	if port <= 0 {
		port = 3306
	}
	if host == "" {
		host = "127.0.0.1"
	}
	return `<?php
// Generated by Exposely — points phpMyAdmin at the Exposely-managed MariaDB.
$cfg['Servers'][1]['host'] = '` + host + `';
$cfg['Servers'][1]['port'] = '` + itoa(port) + `';
$cfg['Servers'][1]['auth_type'] = 'cookie';
$cfg['Servers'][1]['AllowNoPassword'] = true;
`
}

// PhpMyAdminDataDir returns the directory where Exposely keeps its own
// phpMyAdmin copy, independent of EnvKit / Laragon / XAMPP.
func PhpMyAdminDataDir(appDataDir string) string {
	return filepath.Join(appDataDir, "stacks", "phpmyadmin")
}

// EnsureOwnedPhpMyAdmin makes sure Exposely has its own phpMyAdmin copy
// under <appDataDir>/stacks/phpmyadmin:
//
//  1. If the owned copy already exists and looks valid, use it.
//  2. Otherwise locate any installed phpMyAdmin (EnvKit / Laragon /
//     XAMPP / manual) and copy it into the data dir once. After that
//     Exposely no longer depends on the source install - the user can
//     even uninstall EnvKit.
//  3. Returns the directory to serve and whether an owned copy exists.
//
// The copy skips junk (node_modules-style caches are not a thing here,
// but EnvKit's opcache/temp files are) and is idempotent: an existing
// owned copy is never re-copied over.
func EnsureOwnedPhpMyAdmin(appDataDir string) (string, bool) {
	owned := PhpMyAdminDataDir(appDataDir)
	if isPhpMyAdminDir(owned) {
		return owned, true
	}

	source, ok := DetectPhpMyAdmin()
	if !ok {
		return "", false
	}
	if err := CopyDir(source, owned); err != nil {
		return "", false
	}
	// Guard against a partial copy (e.g. files locked by a running
	// source install): only accept the copy when it validates.
	if !isPhpMyAdminDir(owned) {
		return "", false
	}
	return owned, true
}

// copyDirSkip lists directory names excluded when copying an install
// into Exposely's data dir.
var copyDirSkip = map[string]bool{
	"tmp":       true,
	"temp":      true,
	"node_modules": true,
	".git":      true,
}

// CopyDir recursively copies a directory tree. Existing files in dst
// are overwritten; directories are merged. Symlinks are copied as
// files (read through), which is fine for phpMyAdmin's layout.
func CopyDir(src, dst string) error {
	info, err := os.Stat(src)
	if err != nil {
		return err
	}
	if !info.IsDir() {
		return fmt.Errorf("source is not a directory: %s", src)
	}
	if err := os.MkdirAll(dst, 0o755); err != nil {
		return err
	}
	entries, err := os.ReadDir(src)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() {
			if copyDirSkip[strings.ToLower(name)] {
				continue
			}
			if err := CopyDir(filepath.Join(src, name), filepath.Join(dst, name)); err != nil {
				return err
			}
			continue
		}
		if err := copyFile(filepath.Join(src, name), filepath.Join(dst, name)); err != nil {
			// A source file locked by a running process should not fail
			// the whole copy; phpMyAdmin works without e.g. a busy log.
			continue
		}
	}
	return nil
}

func copyFile(src, dst string) error {
	data, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return err
	}
	return os.WriteFile(dst, data, 0o644)
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	neg := n < 0
	if neg {
		n = -n
	}
	var buf [20]byte
	i := len(buf)
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n /= 10
	}
	if neg {
		i--
		buf[i] = '-'
	}
	return string(buf[i:])
}
