// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Bootstrap():Promise<models.AppState>;

export function BrowseProjectFolder(arg1:string):Promise<string>;

export function CreateTunnel():Promise<models.AppState>;

export function DeleteProject(arg1:string):Promise<models.AppState>;

export function OpenConfigFile():Promise<void>;

export function OpenPublicURL(arg1:string):Promise<void>;

export function OpenSettingsFile():Promise<void>;

export function RefreshState():Promise<models.AppState>;

export function RunNpmBuild(arg1:string):Promise<void>;

export function SaveProject(arg1:models.ProjectPreset):Promise<models.AppState>;

export function SaveSettings(arg1:models.AppSettings):Promise<models.AppState>;

export function ShareProject(arg1:string):Promise<models.AppState>;

export function ShareProjectWithRandomURL(arg1:string):Promise<models.AppState>;

export function StartQuickTunnel(arg1:string):Promise<models.AppState>;

export function StartTunnel():Promise<models.AppState>;

export function StopTunnel():Promise<models.AppState>;

export function TestProject(arg1:string):Promise<string>;
