// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicense(arg1) {
  return window['go']['main']['App']['ActivateLicense'](arg1);
}

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function BrowseProjectFolder(arg1) {
  return window['go']['main']['App']['BrowseProjectFolder'](arg1);
}

export function ClearLicense() {
  return window['go']['main']['App']['ClearLicense']();
}

export function CreateTunnel() {
  return window['go']['main']['App']['CreateTunnel']();
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function EnsureCloudflared() {
  return window['go']['main']['App']['EnsureCloudflared']();
}

export function InstallCloudflared() {
  return window['go']['main']['App']['InstallCloudflared']();
}

export function OpenConfigFile() {
  return window['go']['main']['App']['OpenConfigFile']();
}

export function OpenPublicURL(arg1) {
  return window['go']['main']['App']['OpenPublicURL'](arg1);
}

export function OpenSettingsFile() {
  return window['go']['main']['App']['OpenSettingsFile']();
}

export function RefreshState() {
  return window['go']['main']['App']['RefreshState']();
}

export function RunNpmBuild(arg1) {
  return window['go']['main']['App']['RunNpmBuild'](arg1);
}

export function SaveProject(arg1) {
  return window['go']['main']['App']['SaveProject'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ShareProject(arg1) {
  return window['go']['main']['App']['ShareProject'](arg1);
}

export function ShareProjectWithRandomURL(arg1) {
  return window['go']['main']['App']['ShareProjectWithRandomURL'](arg1);
}

export function StartQuickTunnel(arg1) {
  return window['go']['main']['App']['StartQuickTunnel'](arg1);
}

export function StartTunnel() {
  return window['go']['main']['App']['StartTunnel']();
}

export function StopTunnel() {
  return window['go']['main']['App']['StopTunnel']();
}

export function TestProject(arg1) {
  return window['go']['main']['App']['TestProject'](arg1);
}
